In [ ]:
import numpy as np

arr_1 = np.array([1, 2, 3, 4, 5] * 2)

print(arr_1)




[1 2 3 4 5]


In [10]:
import numpy as np

arr = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print(arr)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
import numpy as np

arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ], [
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]
    ]
])

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)
print(arr.size)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
int64
(3, 3, 3)
3
8
27


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], dtype='i1').dtype
print(arr)


int8


In [22]:
import numpy as np

arr_1 = np.array([1, 2, 3]) # 넘파이 배열 1
arr_2 = np.array([4, 5, 6]) # 넘파이 배열 2
print(arr_1 + arr_2) # 덧셈

list_1 = [1, 2, 3] # 파이썬 리스트 1
list_2 = [4, 5, 6] # 파이썬 리스트 2

print(list_1 + list_2) # 리스트 덧셈

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [23]:
list_1 = [1, 2, 3] # 파이썬 리스트 1
list_2 = [4, 5, 6] # 파이썬 리스트 2
rs = [ x + y for x, y in zip(list_1, list_2) ]

print(rs) # 리스트 덧셈




[5, 7, 9]


In [ ]:

c = np.array(('i', 'j', 'k')) # 문자열 배열
print(c)
print(c.dtype) # 문자열 배열의 데이터 타입









['i' 'j' 'k']
<U1


In [32]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
int64
8


In [ ]:
import numpy as np

scores = np.random.randint(0, 101, size=(3, 4, 3))
# 각 학급의 4명의 학생, 각 학생이 3과목의 시험 점수를 가지고 있는 경우 배열 생성
print("학급별 학생들의 점수 배열 (3차원 배열)")
print(scores)

학급별 학생들의 점수 배열 (3차원 배열)
[[[ 9 78 55]
  [71 10 23]
  [50 98 11]
  [99 37 80]]

 [[23 27 76]
  [ 9  4 93]
  [28 69 45]
  [86 16 12]]

 [[74 24 83]
  [67 12 39]
  [21 23 20]
  [28 33 27]]]


In [39]:
import numpy as np


print(np.zeros(shape=(2, 3), dtype=np.int8))

print(np.zeros((3,4), dtype=int))

print(np.ones((2, 3, 4)))

print(np.empty((2, 3)))

[[0 0 0]
 [0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[0. 0. 0.]
 [0. 0. 0.]]
