In [29]:
import numpy as np



In [31]:
p_list = np.array([900, 200, 300, 99, 54, 80])
print("This is a list into numpy array:\n", p_list)

This is a list into numpy array:
 [900 200 300  99  54  80]


In [33]:
print("Type: ", type(p_list))

Type:  <class 'numpy.ndarray'>


In [35]:
p_tuple = np.array((900, 200, 300, 99, 54, 80))
print("This is a tuple into numpy array:\n", p_tuple)

This is a tuple into numpy array:
 [900 200 300  99  54  80]


In [37]:
zerod_arr = np.array(30)
print("This is a zero-d array:\n", zerod_arr, zerod_arr.ndim)

This is a zero-d array:
 30 0


In [38]:
oned_arr = np.array([1, 2, 3, 4, 5])
print("This is a one-d array:\n", oned_arr, oned_arr.ndim)

This is a one-d array:
 [1 2 3 4 5] 1


In [39]:
twod_arr = np.array([[1, 2, 3], [4, 5, 6]])
print("This is a two-d array:\n", twod_arr, twod_arr.ndim)

This is a two-d array:
 [[1 2 3]
 [4 5 6]] 2


In [ ]:
threed_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("This is a three-d array:\n", threed_arr, threed_arr.ndim)

In [ ]:
linspace_arr = np.linspace(2., 5., 6)
print("This is a linspace array:\n", linspace_arr)

In [56]:
a, b = 0, 1
while a < 1000:
    print(a, end=', ')
    a, b = b, a+b

0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 

In [ ]:
for i in range(10):
    print(i, end=', ')